FROM scratch

ADD cue /cue

ADD ca-certificates.crt /etc/ssl/certs/

WORKDIR /

ARG CUE_DB_HOST
ARG CUE_DB_NAME
ARG CUE_DB_PASS
ARG CUE_DB_USER
ARG CUE_SERVER_PORT

ENV CUE_DB_HOST $CUE_DB_HOST
ENV CUE_DB_NAME $CUE_DB_NAME
ENV CUE_DB_PASS $CUE_DB_PASS
ENV CUE_DB_USER $CUE_DB_USER
ENV CUE_DB_USER $CUE_DB_USER

CMD ["/cue"]

EXPOSE $CUE_SERVER_PORT